[theme]
primaryColor = "#3b82f6"
backgroundColor = "#050505"
secondaryBackgroundColor = "#0c0c0c"
textColor = "#f0f0f0"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
